In [14]:
import torch
from torch import nn
import math
torch.manual_seed(1)

m = nn.Sigmoid()
sfm = nn.Softmax(dim=1)
loss = nn.BCELoss()
loss2 = nn.BCEWithLogitsLoss()
input = torch.randn(3, 2, requires_grad=True) 
target = torch.empty(3).random_(2) #target as lable
pinput = sfm(input) # change input to probability vector

print(input)
print(pinput)

print(pinput[:,1])
print(target)

output = loss(pinput[:,1], target)
#-log(1-0.4027)-log(0.6364)-log(0.5710)
print((-math.log(1-0.4027)-math.log(0.6364)-math.log(0.5710))/3)
print(output)



tensor([[ 0.6614,  0.2669],
        [ 0.0617,  0.6213],
        [-0.4519, -0.1661]], requires_grad=True)
tensor([[0.5973, 0.4027],
        [0.3636, 0.6364],
        [0.4290, 0.5710]], grad_fn=<SoftmaxBackward0>)
tensor([0.4027, 0.6364, 0.5710], grad_fn=<SelectBackward0>)
tensor([0., 1., 1.])
0.5092099436961697
tensor(0.5092, grad_fn=<BinaryCrossEntropyBackward0>)


In [15]:
torch.manual_seed(1)

m = nn.Sigmoid()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
pinput = m(input)
print(input)
print(pinput)
print(target)

output = loss(pinput, target)
print(output)


output2 = loss2(input, target)

print(output2)

# -log(0.6596)-log(1-0.5663)-log(1-0.5154)
print((-math.log(0.6596)-math.log(1-0.5663)-math.log(1-0.5154))/3)



tensor([0.6614, 0.2669, 0.0617], requires_grad=True)
tensor([0.6596, 0.5663, 0.5154], grad_fn=<SigmoidBackward0>)
tensor([1., 0., 0.])
tensor(0.6587, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6587, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
0.6586517956790737


In [16]:
torch.manual_seed(1)
# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
pinput = sfm(input)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)

print(input)
print(pinput) 
print(target)
print(output)

# -log(0.1563)-log(0.1035)-log(0.2015) 
print((-math.log(0.1563)-math.log(0.1035)-math.log(0.2015))/3)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631],
        [-0.8923, -0.0583, -0.1955, -0.9656,  0.4224]], requires_grad=True)
tensor([[0.2847, 0.1919, 0.1563, 0.2735, 0.0935],
        [0.2450, 0.0631, 0.4237, 0.1035, 0.1647],
        [0.1004, 0.2311, 0.2015, 0.0933, 0.3738]], grad_fn=<SoftmaxBackward0>)
tensor([2, 3, 2])
tensor(1.9087, grad_fn=<NllLossBackward0>)
1.9087092018089395


In [17]:
torch.manual_seed(1)
# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
pinput = sfm(input)
target = torch.randn(3, 5).softmax(dim=1)
output = loss(input, target)

print(input)
print(target)
print(output)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631],
        [-0.8923, -0.0583, -0.1955, -0.9656,  0.4224]], requires_grad=True)
tensor([[0.3575, 0.1796, 0.1642, 0.0568, 0.2419],
        [0.8422, 0.0037, 0.1153, 0.0065, 0.0323],
        [0.0326, 0.2089, 0.6596, 0.0793, 0.0196]])
tensor(1.5697, grad_fn=<DivBackward1>)
